"""
Generates Assets/Scripts/World/Art/SignFontData.cs: a signed-distance-field bitmap font used to letter
road signs at any size. Source font: DejaVu Sans Bold (Bitstream Vera licence; see header of the output).

  pip install pillow numpy scipy
  python3 Tools/fontgen/gen_sdf_font.py [path/to/DejaVuSans-Bold.ttf]
"""
import base64, sys, os
import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt

FONT = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
HI = 128          # render size (px per em)
DOWN = 4          # downsample factor -> 32 px per em in the SDF
SPREAD = 4.0      # SDF spread in low-res pixels
PAD = 6           # low-res padding around each glyph

font = ImageFont.truetype(FONT, HI)
ascent, descent = font.getmetrics()
chars = [chr(c) for c in range(32, 127)]
glyphs = []
blob = bytearray()
for ch in chars:
    adv = font.getlength(ch)
    bbox = font.getbbox(ch)  # relative to origin at top-left of ascent
    if ch == " " or bbox[2] <= bbox[0]:
        glyphs.append((len(blob), 0, 0, 0, 0, adv / DOWN))
        continue
    x0, y0, x1, y1 = bbox
    padh = PAD * DOWN
    w = (x1 - x0) + 2 * padh
    h = (y1 - y0) + 2 * padh
    w += (-w) % DOWN
    h += (-h) % DOWN
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((padh - x0, padh - y0), ch, font=font, fill=255)
    a = np.asarray(img) > 127
    inside = distance_transform_edt(a)
    outside = distance_transform_edt(~a)
    sd = (outside - inside) / DOWN          # >0 outside, <0 inside, in low-res px
    sd = sd.reshape(h // DOWN, DOWN, w // DOWN, DOWN).mean(axis=(1, 3))
    v = np.clip(128 - sd / SPREAD * 127, 0, 255).astype(np.uint8)
    lw, lh = w // DOWN, h // DOWN
    # offset of bitmap top-left from the pen position, y measured downward from the baseline
    ox = (x0 - padh) / DOWN
    oy = (y0 - padh - ascent) / DOWN
    off = len(blob)
    blob += v.tobytes()
    glyphs.append((off, lw, lh, ox, oy, adv / DOWN))

lines = []
lines.append("// <auto-generated> by Tools/fontgen/gen_sdf_font.py - do not edit.")
lines.append("// Signed distance field rendering of DejaVu Sans Bold.")
lines.append("// DejaVu fonts are derived from Bitstream Vera: Copyright (c) 2003 Bitstream, Inc. All Rights Reserved.")
lines.append("// Bitstream Vera is a trademark of Bitstream, Inc. Licence: https://dejavu-fonts.github.io/License.html")
lines.append("namespace UKCity.World.Art")
lines.append("{")
lines.append("    internal static class SignFontData")
lines.append("    {")
lines.append(f"        public const float Ascent = {ascent / DOWN:.3f}f;")
lines.append(f"        public const float Descent = {descent / DOWN:.3f}f;")
lines.append(f"        public const float Spread = {SPREAD:.1f}f;")
lines.append("        public const int FirstChar = 32;")
lines.append("        // offset, width, height, offsetX, offsetY, advance")
lines.append("        public static readonly float[] Metrics =")
lines.append("        {")
for g in glyphs:
    lines.append(f"            {g[0]}, {g[1]}, {g[2]}, {g[3]:.2f}f, {g[4]:.2f}f, {g[5]:.2f}f,")
lines.append("        };")
b64 = base64.b64encode(bytes(blob)).decode()
lines.append("        public const string Data =")
chunks = [b64[i:i + 120] for i in range(0, len(b64), 120)]
for i, c in enumerate(chunks):
    lines.append(f"            \"{c}\"" + (";" if i == len(chunks) - 1 else " +"))
lines.append("    }")
lines.append("}")
out = os.path.join(os.path.dirname(__file__), "..", "..", "Assets", "Scripts", "World", "Art", "SignFontData.cs")
open(out, "w").write("\n".join(lines) + "\n")
print("glyphs", len(glyphs), "bytes", len(blob), "->", os.path.normpath(out))
