name: Compile check

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build (legacy Input Manager)
        run: dotnet build Tools/compile-check -nologo -warnaserror
      - name: Build (Input System)
        run: dotnet build Tools/compile-check -nologo -warnaserror -p:NewInput=true --no-incremental
